"""skill deleted

Revision ID: 65b23b3d40b8
Revises: 9caf44674346
Create Date: 2024-09-25 21:33:17.749925

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
import sqlmodel


# revision identifiers, used by Alembic.
revision: str = '65b23b3d40b8'
down_revision: Union[str, None] = '9caf44674346'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('tasktime', 'skill')
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('tasktime', sa.Column('skill', sa.INTEGER(), autoincrement=False, nullable=True))
    # ### end Alembic commands ###
